### ISSUE TITLE
TODO: to make an another type of the extensions - an additional button for any `function`.

### ISSUE THREAD

**Issue by PeterVoronov** [PeterVoronov/ioBrokerTelegramMenuScript#4]
The main idea - to make possible to add new "device" buttons for any function, which have to exec "button extension", which can do anything (send a file/image to chat, make some calculations and return some text result, etc...).
The main parameter have to be an any state of the 'function' - it have to be configurable via `Functions` menu.

**Comment by kandkhm** [comment]
Implemented by #72 and postfixes.

**Comment by PeterVoronov** [comment]
Implemented by #72 and postfixes.
